export const bathroomProject = {
  key: "bathroom",
  label: "Badeværelse",
  description: "Nyt badeværelse eller renovering af eksisterende bad",
  intro: "Jeg hjælper dig med at afklare badeværelsesprojektet trin for trin.",
  categoryQuestion: "Hvilken stil eller retning passer bedst?",
  categoryOptions: [
    {
      key: "modern",
      label: "Moderne",
      description: "Rene linjer, rolige farver og et stramt look",
      image: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1200&q=80",
      priceRange: [15000, 45000],
      factor: 1.12,
    },
    {
      key: "classic",
      label: "Klassisk",
      description: "Tidløst, funktionelt og sikkert valg",
      image: "https://images.unsplash.com/photo-1484154218962-a197022b5858?auto=format&fit=crop&w=1200&q=80",
      priceRange: [10000, 30000],
      factor: 1.0,
    },
    {
      key: "spa",
      label: "Spa",
      description: "Luksus, varme toner og hotelstemning",
      image: "https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=1200&q=80",
      priceRange: [25000, 70000],
      factor: 1.24,
    },
    {
      key: "budget",
      label: "Prisvenlig",
      description: "Fornuftige valg med fokus på økonomi",
      image: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1200&q=80",
      priceRange: [0, 15000],
      factor: 0.9,
    },
  ],
  sizeQuestion: "Hvor stort er badeværelset cirka?",
  sizeOptions: [
    { key: "xs", label: "2-4 m²", factor: 0.85, priceRange: [0, 20000] },
    { key: "sm", label: "4-6 m²", factor: 1.0, priceRange: [15000, 35000] },
    { key: "md", label: "6-9 m²", factor: 1.18, priceRange: [30000, 55000] },
    { key: "lg", label: "9-12 m²", factor: 1.34, priceRange: [50000, 90000] },
  ],
  detailQuestion: "Beskriv konkret hvad der skal laves.",
  detailPlaceholder: "Fx: Jeg vil have totalrenoveret badeværelset, flyttet bruseren, lavet niche i væggen, gulvvarme og et væghængt toilet...",
  photoQuestion: "Har du billeder af det nuværende badeværelse?",
  elementGroups: [
    {
      key: "armatur",
      label: "Armaturer",
      helperText: "Brug prisniveau som et tidligt pejlemærke.",
      options: [
        { key: "basic", label: "Standard", priceRange: [4000, 9000] },
        { key: "mid", label: "Mellemklasse", priceRange: [9000, 17000] },
        { key: "premium", label: "Design", priceRange: [17000, 30000] },
      ],
    },
    {
      key: "furniture",
      label: "Møbler",
      helperText: "Møbler og opbevaring har ofte stor betydning for totalen.",
      options: [
        { key: "basic", label: "Enkelt møbel", priceRange: [6000, 12000] },
        { key: "mid", label: "God kvalitet", priceRange: [12000, 22000] },
        { key: "premium", label: "Eksklusivt møbel", priceRange: [22000, 38000] },
      ],
    },
    {
      key: "shower",
      label: "Bruseløsning",
      helperText: "Rain shower og glasløsninger løfter ofte prisen.",
      options: [
        { key: "basic", label: "Standard løsning", priceRange: [7000, 14000] },
        { key: "mid", label: "Rain shower", priceRange: [14000, 24000] },
        { key: "premium", label: "Eksklusiv løsning", priceRange: [24000, 42000] },
      ],
    },
    {
      key: "tiles",
      label: "Fliser og overflader",
      helperText: "Store fliser og designvalg påvirker totalen markant.",
      options: [
        { key: "basic", label: "Standard", priceRange: [15000, 28000] },
        { key: "mid", label: "Pæn mellemklasse", priceRange: [28000, 42000] },
        { key: "premium", label: "Store / designfliser", priceRange: [42000, 70000] },
      ],
    },
  ],
  estimateBase: { low: 70000, high: 105000 },
  feedback: {
    midThreshold: 190000,
    highThreshold: 320000,
    low: "Det her ligner en mere prisbevidst løsning med fokus på de vigtigste valg først.",
    mid: "Det her ligger i et solidt mellemleje, hvor mange komplette badeværelsesprojekter ender.",
    high: "Det her ligner et større badeværelsesprojekt med flere valg i den dyre ende.",
  },
};
