export const kitchenProject = {
  key: "kitchen",
  label: "Køkken",
  description: "Nyt køkken eller renovering af eksisterende køkken",
  intro: "Jeg hjælper dig med at afklare køkkenprojektet trin for trin.",
  categoryQuestion: "Hvilken stil eller retning passer bedst?",
  categoryOptions: [
    {
      key: "modern",
      label: "Moderne",
      description: "Rene linjer og et stramt køkkenudtryk",
      image: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?auto=format&fit=crop&w=1200&q=80",
      priceRange: [15000, 45000],
      factor: 1.12,
    },
    {
      key: "classic",
      label: "Klassisk",
      description: "Tidløst og sikkert valg",
      image: "https://images.unsplash.com/photo-1484154218962-a197022b5858?auto=format&fit=crop&w=1200&q=80",
      priceRange: [10000, 30000],
      factor: 1.0,
    },
    {
      key: "premium",
      label: "Eksklusivt",
      description: "Design, høj finish og flere specialvalg",
      image: "https://images.unsplash.com/photo-1489515217757-5fd1be406fef?auto=format&fit=crop&w=1200&q=80",
      priceRange: [25000, 70000],
      factor: 1.24,
    },
    {
      key: "budget",
      label: "Prisvenligt",
      description: "Fornuftig løsning med fokus på økonomi",
      image: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1200&q=80",
      priceRange: [0, 15000],
      factor: 0.9,
    },
  ],
  sizeQuestion: "Hvor stort er køkkenet cirka?",
  sizeOptions: [
    { key: "xs", label: "5-8 m²", factor: 0.88, priceRange: [0, 25000] },
    { key: "sm", label: "8-12 m²", factor: 1.0, priceRange: [20000, 45000] },
    { key: "md", label: "12-18 m²", factor: 1.18, priceRange: [40000, 80000] },
    { key: "lg", label: "18+ m²", factor: 1.34, priceRange: [70000, 130000] },
  ],
  detailQuestion: "Beskriv konkret hvad der skal laves.",
  detailPlaceholder: "Fx: Jeg vil have nyt køkken med køkkenø, nye hvidevarer, ny bordplade, ændret layout og bedre opbevaring...",
  photoQuestion: "Har du billeder af det nuværende køkken?",
  elementGroups: [
    {
      key: "cabinets",
      label: "Køkkenelementer",
      helperText: "Elementer er ofte den største post i budgettet.",
      options: [
        { key: "basic", label: "Standard", priceRange: [25000, 50000] },
        { key: "mid", label: "Mellemklasse", priceRange: [50000, 90000] },
        { key: "premium", label: "Special / design", priceRange: [90000, 160000] },
      ],
    },
    {
      key: "countertop",
      label: "Bordplade",
      helperText: "Materialevalget kan ændre totalen markant.",
      options: [
        { key: "basic", label: "Laminat", priceRange: [5000, 15000] },
        { key: "mid", label: "Komposit / træ", priceRange: [15000, 35000] },
        { key: "premium", label: "Sten / eksklusiv", priceRange: [35000, 70000] },
      ],
    },
    {
      key: "appliances",
      label: "Hvidevarer",
      helperText: "Pakken af hvidevarer har stor betydning for spændet.",
      options: [
        { key: "basic", label: "Basispakke", priceRange: [15000, 30000] },
        { key: "mid", label: "God kvalitet", priceRange: [30000, 60000] },
        { key: "premium", label: "Premium pakke", priceRange: [60000, 120000] },
      ],
    },
    {
      key: "sink",
      label: "Vask og armatur",
      helperText: "Små valg her påvirker stadig totalen.",
      options: [
        { key: "basic", label: "Standard", priceRange: [4000, 9000] },
        { key: "mid", label: "Mellemklasse", priceRange: [9000, 18000] },
        { key: "premium", label: "Design", priceRange: [18000, 35000] },
      ],
    },
  ],
  estimateBase: { low: 90000, high: 140000 },
  feedback: {
    midThreshold: 200000,
    highThreshold: 350000,
    low: "Det her ligner en mere prisbevidst køkkenløsning med fokus på de vigtigste valg først.",
    mid: "Det her ligger i et solidt mellemleje, hvor mange komplette køkkenprojekter ender.",
    high: "Det her ligner et større køkkenprojekt med flere valg i den dyre ende.",
  },
};
