export const vvsProject = {
  key: "vvs",
  label: "VVS",
  description: "Lækage, varme, installationer og reparationer",
  intro: "Jeg hjælper dig med at afklare din VVS-opgave, så du får et mere realistisk prisestimat og et bedre tilbudsgrundlag.",
  categoryQuestion: "Hvad drejer opgaven sig om?",
  categoryOptions: [
    {
      key: "leak",
      label: "Lækage / akut",
      description: "Dryp, skjult fugt eller akut vandproblem",
      image: "https://images.unsplash.com/photo-1585704032915-c3400ca199e7?auto=format&fit=crop&w=1200&q=80",
      priceRange: [0, 4000],
      factor: 1.05,
    },
    {
      key: "bathroom",
      label: "Bad / sanitet",
      description: "Toilet, bruser, vask og armatur",
      image: "https://images.unsplash.com/photo-1620626011761-996317b8d101?auto=format&fit=crop&w=1200&q=80",
      priceRange: [1000, 8000],
      factor: 1.08,
    },
    {
      key: "heat",
      label: "Varme / gulvvarme",
      description: "Radiator, gulvvarme og varmeanlæg",
      image: "https://images.unsplash.com/photo-1631049307264-da0ec9d70304?auto=format&fit=crop&w=1200&q=80",
      priceRange: [3000, 20000],
      factor: 1.16,
    },
    {
      key: "kitchen",
      label: "Køkken / armatur",
      description: "Vask, armatur eller opvaskemaskine",
      image: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?auto=format&fit=crop&w=1200&q=80",
      priceRange: [1000, 6000],
      factor: 1.0,
    },
    {
      key: "replace",
      label: "Udskiftning / reparation",
      description: "Udskiftning af eksisterende eller mindre reparation",
      image: "https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?auto=format&fit=crop&w=1200&q=80",
      priceRange: [1000, 7000],
      factor: 0.98,
    },
  ],
  sizeQuestion: "Hvor stort område er berørt?",
  sizeOptions: [
    { key: "xs", label: "Én installation / ét punkt", factor: 0.9, priceRange: [0, 1500] },
    { key: "sm", label: "Ét rum", factor: 1.0, priceRange: [1000, 4000] },
    { key: "md", label: "Flere rum", factor: 1.18, priceRange: [3000, 9000] },
    { key: "lg", label: "Større del af boligen", factor: 1.34, priceRange: [8000, 20000] },
  ],
  detailQuestion: "Beskriv konkret hvad der skal laves.",
  detailPlaceholder: "Fx: Det drypper under vasken i køkkenet, eller jeg vil have installeret gulvvarme i badeværelset...",
  photoQuestion: "Har du billeder af det nuværende område? På mobil kan du tage dem direkte fra telefonen.",
  elementGroups: [
    {
      key: "urgency",
      label: "Akuthed",
      helperText: "Brug det som et realistisk niveau for hast og tilgængelighed.",
      options: [
        { key: "now", label: "Akut - lige nu", priceRange: [1500, 5000] },
        { key: "soon", label: "Hurtigst muligt", priceRange: [800, 3000] },
        { key: "planned", label: "Planlagt opgave", priceRange: [0, 1000] },
      ],
    },
    {
      key: "taskType",
      label: "Opgavetype",
      helperText: "Reparation er typisk billigere end ny installation.",
      options: [
        { key: "repair", label: "Reparation", priceRange: [800, 4000] },
        { key: "replace", label: "Udskiftning", priceRange: [1500, 8000] },
        { key: "install", label: "Ny installation", priceRange: [2500, 15000] },
      ],
    },
    {
      key: "materials",
      label: "Materialer",
      helperText: "Hvis håndværker skal levere materialer, løfter det typisk totalprisen.",
      options: [
        { key: "have", label: "Jeg har allerede materialer", priceRange: [0, 0] },
        { key: "need", label: "Håndværker skal levere materialer", priceRange: [1000, 8000] },
        { key: "unknown", label: "Ved ikke endnu", priceRange: [500, 4000] },
      ],
    },
    {
      key: "complexity",
      label: "Kompleksitet",
      helperText: "Skjult arbejde og svær adgang øger som regel prisen.",
      options: [
        { key: "simple", label: "Standard adgang / enkel opgave", priceRange: [0, 1500] },
        { key: "medium", label: "Lidt mere kompleks", priceRange: [1000, 5000] },
        { key: "complex", label: "Svær adgang / skjult arbejde", priceRange: [3000, 12000] },
      ],
    },
  ],
  estimateBase: { low: 1500, high: 6000 },
  feedback: {
    midThreshold: 12000,
    highThreshold: 35000,
    low: "Det her ligner en mindre eller mere standardpræget VVS-opgave.",
    mid: "Det her ligner en klassisk VVS-opgave i mellemlejet.",
    high: "Det her ligner en mere omfattende VVS-opgave, hvor pris og kompleksitet hurtigt kan stige.",
  },
};
